# fly.toml app configuration file generated for no365-myurls on 2023-08-27T15:57:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "no365-myurls"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
